import { getUiLocale } from '@/i18n';

const zh = {
  appName: '评论外链助手',
  dashboard: '运营看板',
  plans: '计划管理',
  settings: '设置',
  filterList: '\u8fc7\u6ee4\u5217\u8868',
  filterListTitle: '\u8fc7\u6ee4\u5217\u8868',
  filterListDescription:
    '\u547d\u4e2d\u540e\u4f1a\u81ea\u52a8\u8df3\u8fc7\u3002\u7cbe\u786e URL \u53ea\u8fc7\u6ee4\u5f53\u524d\u94fe\u63a5\uff1b\u57df\u540d\u540c\u65f6\u5339\u914d\u5b50\u57df\u540d\u3002',
  filterValue: '\u94fe\u63a5\u6216\u57df\u540d',
  filterValuePlaceholder: 'https://example.com/article \u6216 example.com',
  filterMatchType: '\u5339\u914d\u65b9\u5f0f',
  filterKindUrl: '\u7cbe\u786e URL',
  filterKindDomain: '\u57df\u540d\u53ca\u5b50\u57df\u540d',
  addFilterEntry: '\u52a0\u5165\u8fc7\u6ee4\u5217\u8868',
  filterEntries: '\u8fc7\u6ee4\u6761\u76ee\uff08{0}\uff09',
  filterListAutoSkip: '\u540e\u7eed\u9047\u5230\u4f1a\u81ea\u52a8\u8df3\u8fc7',
  filterListEmptyTitle: '\u8fd8\u6ca1\u6709\u8fc7\u6ee4\u94fe\u63a5',
  filterListEmptyHint:
    '\u53ef\u5728\u8fd9\u91cc\u624b\u52a8\u52a0\u5165\uff0c\u4e5f\u53ef\u5728\u5220\u9664\u8ba1\u5212\u94fe\u63a5\u65f6\u52a0\u5165\u3002',
  filterCreatedAt: '\u6dfb\u52a0\u4e8e {0}',
  removeFilterEntry: '\u4ece\u8fc7\u6ee4\u5217\u8868\u79fb\u9664 {0}',
  filterEntryAdded: '\u5df2\u52a0\u5165\u8fc7\u6ee4\u5217\u8868',
  filterEntryRemoved: '\u5df2\u4ece\u8fc7\u6ee4\u5217\u8868\u79fb\u9664',
  filterValueInvalid:
    '\u8bf7\u8f93\u5165\u6709\u6548\u7684 HTTP(S) URL \u6216\u57df\u540d\u3002',
  filterListLoadFailed: '\u8fc7\u6ee4\u5217\u8868\u52a0\u8f7d\u5931\u8d25',
  outboundLinkLibrary: '\u5916\u94fe\u5e93',
  outboundLinkLibraryTitle: '\u5916\u94fe\u5e93',
  outboundLinkLibraryDescription:
    '\u4fdd\u5b58\u53ef\u76f4\u63a5\u6267\u884c\u7684\u535a\u5ba2\u6587\u7ae0 URL\uff0c\u5e76\u8bb0\u5f55 dofollow\u3001nofollow\u3001\u533f\u540d\u8bc4\u8bba\u548c CAPTCHA \u5c5e\u6027\uff0c\u652f\u6301 Excel/CSV/TXT \u6279\u91cf\u5bfc\u5165\u3002',
  outboundLinkUrl: '\u535a\u5ba2\u6587\u7ae0 URL',
  outboundLinkUrlPlaceholder: 'https://example.com/blog/article',
  outboundLinkAdd: '\u6dfb\u52a0\u5916\u94fe',
  outboundLinkEntries: '\u5916\u94fe\uff08{0}\uff09',
  outboundLinkTags: '\u6807\u7b7e',
  outboundLinkAttributes: '\u5916\u94fe\u5c5e\u6027',
  outboundLinkUnmarked: '\u672a\u6807\u6ce8',
  outboundLinkTagDofollow: 'Dofollow',
  outboundLinkTagNofollow: 'Nofollow',
  outboundLinkTagLoginRequired: '\u9700\u8981\u767b\u5f55',
  outboundLinkTagCaptchaRequired: '\u4eba\u673a\u9a8c\u8bc1',
  outboundLinkNoTags: '\u65e0\u6807\u7b7e',
  outboundLinkManualOnly: '\u5b8c\u6574 URL \u7ba1\u7406',
  outboundLinkEmptyTitle: '\u6682\u65e0\u5916\u94fe\u8bb0\u5f55',
  outboundLinkEmptyHint:
    '\u6dfb\u52a0\u7ad9\u70b9\u540e\uff0c\u4e3a\u5b83\u6807\u8bb0\u5916\u94fe\u5c5e\u6027\u4e0e\u4eba\u5de5\u5904\u7406\u6761\u4ef6\u3002',
  outboundLinkSaved: '\u5df2\u4fdd\u5b58\u5230\u5916\u94fe\u5e93',
  outboundLinkUpdated: '\u5916\u94fe\u5df2\u66f4\u65b0',
  outboundLinkRemoved: '\u5df2\u4ece\u5916\u94fe\u5e93\u79fb\u9664',
  outboundLinkUrlInvalid:
    '\u8bf7\u8f93\u5165\u6709\u6548\u7684\u535a\u5ba2\u6587\u7ae0 URL \u6216\u57df\u540d\u3002',
  outboundLinkDuplicate:
    '\u5916\u94fe\u5e93\u5df2\u6709\u8be5\u5b8c\u6574\u94fe\u63a5\u3002',
  outboundLinkAlreadyExists:
    '\u5916\u94fe\u5e93\u5df2\u6709\u8be5\u5b8c\u6574\u94fe\u63a5\u3002',
  outboundLinkTagConflict:
    'Dofollow \u4e0e nofollow \u4e0d\u80fd\u540c\u65f6\u9009\u4e2d\u3002',
  outboundLinkNotFound:
    '\u8be5\u5916\u94fe\u5df2\u4e0d\u5b58\u5728\uff0c\u5df2\u79fb\u9664\u672c\u5730\u663e\u793a\u3002',
  outboundLinkUpdatedAt: '\u66f4\u65b0\u4e8e {0}',
  outboundLinkSave: '\u4fdd\u5b58\u5916\u94fe',
  editOutboundLinkEntry: '\u7f16\u8f91\u5916\u94fe {0}',
  removeOutboundLinkEntry: '\u4ece\u5916\u94fe\u5e93\u79fb\u9664 {0}',
  cancelEdit: '\u53d6\u6d88\u7f16\u8f91',
  outboundLinkLoadFailed: '\u5916\u94fe\u5e93\u52a0\u8f7d\u5931\u8d25',
  outboundLinkDomain: '\u535a\u5ba2\u6587\u7ae0 URL',
  outboundLinkFollowStatus: '\u94fe\u63a5\u5c5e\u6027',
  outboundLinkLoginRequired: '\u662f\u5426\u9700\u8981\u767b\u5f55',
  outboundLinkCaptchaRequired: '\u662f\u5426 CAPTCHA',
  outboundLinkStatDomains: '\u5916\u94fe\u603b\u6570',
  outboundLinkStatDofollow: 'Dofollow',
  outboundLinkStatNofollow: 'Nofollow',
  outboundLinkStatAnonymous: '\u533f\u540d\u8bc4\u8bba',
  outboundLinkStatNoCaptcha: '\u65e0\u9700\u4eba\u673a\u9a8c\u8bc1',
  outboundLinkImport: '\u6279\u91cf\u5bfc\u5165',
  outboundLinkImportPreview: '\u5bfc\u5165\u9884\u89c8',
  outboundLinkImportValidRows: '\u53ef\u5bfc\u5165',
  outboundLinkImportInvalidRows: '\u9519\u8bef\u884c',
  outboundLinkImportConfirm: '\u786e\u8ba4\u5bfc\u5165',
  outboundLinkImportFailed: '\u6587\u4ef6\u89e3\u6790\u5931\u8d25',
  outboundLinkImportCompleted: '\u5916\u94fe\u5e93\u5bfc\u5165\u5b8c\u6210',
  outboundLinkImportRowError: '\u7b2c {0} \u884c\uff1a{1}',
  outboundLinkDownloadTemplate: '\u4e0b\u8f7d\u6a21\u677f',
  outboundLinkSearch: '\u641c\u7d22\u94fe\u63a5\u6216\u57df\u540d',
  outboundLinkFilter: '\u7b5b\u9009\u5c5e\u6027',
  outboundLinkFilterAll: '\u5168\u90e8',
  outboundLinkSelect: '\u4ece\u5916\u94fe\u5e93\u9009\u62e9',
  outboundLinkAddToPlan: '\u5bfc\u5165\u5230\u8ba1\u5212',
  outboundLinkSelectedCount: '\u5df2\u9009\u62e9 {0} \u4e2a',
  outboundLinkSelectCurrentPage: '\u5168\u9009\u672c\u9875',
  outboundLinkClearCurrentPage: '\u53d6\u6d88\u5168\u9009\u672c\u9875',
  outboundLinkSelectEmptyHint:
    '\u6682\u65e0\u53ef\u9009\u5916\u94fe\uff0c\u53ef\u5148\u524d\u5f80\u5916\u94fe\u5e93\u6dfb\u52a0\u3002',
  outboundLinkOpenLibrary: '\u524d\u5f80\u5916\u94fe\u5e93',
  connected: '扩展已连接',
  disconnected: '扩展未连接',
  version: '版本',
  dashboardTitle: '运营看板',
  plansTitle: '计划管理',
  refresh: '刷新',
  refreshing: '正在刷新',
  activePlans: '活跃计划',
  processed: '已处理',
  submitted: '成功',
  failed: '失败',
  todaySchedule: '今日排程',
  runToday: '运行今日批次',
  running: '运行中',
  runBatch: '运行此批次',
  viewDetail: '查看详情',
  batchProgress: '第 {0} / {1} 批',
  linkCount: '{0} 条',
  nextBatch: '下一批',
  noNextBatch: '已经是最后一批',
  noSchedule: '今天没有待运行批次',
  noScheduleHint: '新建计划后，最早的待处理批次会显示在这里。',
  liveRun: '实时运行',
  currentTarget: '当前处理',
  waitingToRun: '等待运行',
  noActiveRun: '当前没有正在运行的批次',
  noActiveRunHint: '从今日排程或计划详情启动一个批次。',
  planProgress: '计划进度',
  batchProgressLabel: '本批进度（第 {0} 批）',
  remaining: '剩余',
  openCurrent: '打开当前链接',
  stopBatch: '停止批次',
  continueBatch: '处理完，继续运行',
  websiteStats: '网站统计',
  promotingSites: '按推广网站',
  targetDomains: '按目标博客域名',
  website: '网站',
  total: '总数',
  recentFailures: '近期失败',
  allFailures: '查看计划详情',
  noFailures: '最近没有失败链接',
  errorCode: '错误码',
  retry: '重试',
  retrySelected: '重试选中项',
  retrying: '正在重试',
  planList: '计划列表',
  planCount: '共 {0} 个计划',
  newPlan: '新建计划',
  addPromotingSite: '新建推广网站',
  addPromotingSiteOption: '＋ 新建推广网站…',
  active: '进行中',
  completed: '已完成',
  archived: '已归档',
  notStarted: '未开始',
  completedWithErrors: '完成但有错误',
  blocked: '需要处理',
  interrupted: '已停止',
  planDetail: '计划详情',
  linksAndBatch: '{0} 条链接 · 每批 {1} 条 · 已完成 {2} 条',
  batchNumber: '第 {0} 批',
  currentBatch: '当前批次',
  targets: '链接列表',
  targetAddress: '链接地址',
  status: '状态',
  updatedAt: '更新时间',
  targetActions: '\u64cd\u4f5c',
  deleteTargetAction: '\u5220\u9664 {0}',
  deleteTargetUnavailable:
    '\u5f53\u524d\u6279\u6b21\u6b63\u5728\u8fd0\u884c\uff0c\u6682\u4e0d\u80fd\u5220\u9664',
  deleteTargetTitle: '\u5220\u9664\u8fd9\u4e2a\u94fe\u63a5\uff1f',
  deleteTargetDescription:
    '\u8fd9\u4f1a\u4ece\u5f53\u524d\u8ba1\u5212\u4e2d\u79fb\u9664\u8be5\u94fe\u63a5\u53ca\u5176\u8fd0\u884c\u8bb0\u5f55\u3002',
  deleteTargetPublishedHint:
    '\u5982\u679c\u8bc4\u8bba\u5df2\u53d1\u5e03\uff0c\u5220\u9664\u8bb0\u5f55\u4e0d\u4f1a\u64a4\u56de\u5df2\u53d1\u5e03\u7684\u8bc4\u8bba\u3002',
  addToFilterList: '\u540c\u65f6\u52a0\u5165\u8fc7\u6ee4\u5217\u8868',
  addToFilterListHint:
    '\u4ee5\u540e\u9047\u5230\u8fd9\u4e2a\u7cbe\u786e\u94fe\u63a5\u4f1a\u81ea\u52a8\u8df3\u8fc7\u3002',
  targetDeleted: '\u5df2\u4ece\u8ba1\u5212\u4e2d\u5220\u9664\u94fe\u63a5',
  targetDeletedAndFiltered:
    '\u5df2\u5220\u9664\u94fe\u63a5\u5e76\u52a0\u5165\u8fc7\u6ee4\u5217\u8868',
  confirmTargetDelete: '\u5220\u9664\u94fe\u63a5',
  previousPage: '上一页',
  nextPage: '下一页',
  pageOf: '第 {0} / {1} 页',
  noTargets: '此批次还没有链接数据',
  submittedStatus: '已提交',
  publishedStatus: '已显示',
  pendingModerationStatus: '已提交，待审核',
  unconfirmedStatus: '提交结果未知',
  failedStatus: '失败',
  pendingStatus: '待处理',
  filteredStatus: '\u5df2\u8fc7\u6ee4',
  queuedStatus: '排队中',
  openingStatus: '打开页面',
  analyzingStatus: '分析页面',
  generatingStatus: '正在生成评论',
  preparedStatus: '准备提交',
  submittingStatus: '正在提交',
  verifyingStatus: '正在验证',
  loginRequiredStatus: '需要登录',
  captchaRequiredStatus: '需要验证码',
  noFormStatus: '未找到评论表单',
  validationErrorStatus: '表单校验失败',
  stoppedStatus: '已停止',
  unknownStatus: '未知',
  runStage: '运行阶段',
  nextRunCard: '下一批：第 {0} 批，{1} 条',
  expectedStart: '将在当前批次结束后可运行',
  planName: '计划名称',
  planNamePlaceholder: '例如：Seed Audio 七月外链计划',
  promotingWebsite: '推广网站',
  promotingSiteCreateDescription: '新建一个可在计划中使用的推广网站。',
  promotingSiteName: '推广网站名称',
  promotingSiteNamePlaceholder: '例如：Seed Audio',
  promotingSiteUrl: '推广网站 URL',
  promotingSiteUrlPlaceholder: 'example.com',
  promotingSiteDisplayName: '评论显示名称',
  promotingSiteEmail: '评论邮箱',
  promotingSiteLinkMode: '链接写入方式',
  promotingSiteLinkModeATagNewline: 'a 标签（换行）',
  promotingSiteLinkModeWebsiteField: '优先填写 Website 字段',
  promotingSiteLinkModeCommentOnly: '仅评论正文',
  addingPromotingSite: '正在保存',
  promotingSiteCreated: '推广网站已创建',
  promotingSiteNameRequired: '请填写推广网站名称。',
  promotingSiteNameTooLong: '推广网站名称不能超过 100 个字符。',
  promotingSiteUrlRequired: '请填写推广网站 URL。',
  promotingSiteUrlInvalid: '请输入有效的 HTTP(S) URL 或域名。',
  promotingSiteEmailInvalid: '请输入有效邮箱。',
  promotingSiteDuplicate: '该推广网站已存在。',
  promotingSiteLimit: '最多可配置 20 个推广网站。',
  promotingSiteCreateFailed: '推广网站保存失败，请重试。',
  renamePlan: '\u4fee\u6539\u8ba1\u5212\u540d\u79f0',
  renamePlanTitle: '\u4fee\u6539\u8ba1\u5212\u540d\u79f0',
  savePlanName: '\u4fdd\u5b58\u540d\u79f0',
  planRenamed: '\u8ba1\u5212\u540d\u79f0\u5df2\u66f4\u65b0',
  websiteFieldUrl: '\u63a8\u5e7f\u843d\u5730\u9875 / Website \u5b57\u6bb5 URL',
  websiteFieldUrlPlaceholder: 'https://example.com/landing-page/',
  websiteFieldUrlHint:
    '\u5982\u679c\u535a\u5ba2\u8bc4\u8bba\u8868\u5355\u6709 Website / URL \u8f93\u5165\u6846\uff0c\u8fd0\u884c\u65f6\u4f1a\u81ea\u52a8\u586b\u5165\u6b64\u5730\u5740\uff1b\u8bc4\u8bba\u6b63\u6587\u4e0d\u4f1a\u91cd\u590d\u653e\u94fe\u63a5\u3002',
  websiteFieldInlineHint:
    '\u5f53\u524d\u7b56\u7565\u4e3a\u201c\u8bc4\u8bba\u5185\u81ea\u7136\u94fe\u63a5\u201d\uff0c\u4e0d\u4f1a\u586b\u5165 Website \u5b57\u6bb5\u3002',
  targetUrls: '目标博客 URL',
  targetUrlsPlaceholder: '每行粘贴一个 URL，最多 2,000 条',
  batchSize: '每批数量',
  importFile: '导入 TXT / CSV / Excel',
  fileHint: '支持 .txt、.csv、.xlsx 与 .xls，文件内容会追加到输入框。',
  preview: '批量预览',
  validLinks: '有效链接',
  duplicateLinks: '重复链接',
  invalidLinks: '无效链接',
  batches: '预计批次',
  showMore: '还有 {0} 条未显示',
  createPlan: '保存计划',
  creatingPlan: '正在保存',
  cancel: '取消',
  close: '关闭',
  planCreated: '计划已创建',
  archivePlan: '归档计划',
  archiveConfirm: '归档后计划将只读，但所有运行记录仍会保留。',
  deleteForever: '永久删除',
  deleteConfirmTitle: '永久删除这个计划？',
  deleteConfirm: '此操作会删除计划、批次、链接结果和错误历史，无法恢复。',
  confirmDelete: '确认永久删除',
  startNextBatch: '运行下一批',
  resumeBatch: '恢复批次',
  errorDetail: '错误详情',
  linkProcessDetail: '外链处理详情',
  latestUpdate: '最新处理结果',
  processingFlow: '插件处理流程',
  writtenContent: '写入内容',
  noWrittenContent: '该次处理尚未生成可写入的评论内容。',
  friendlyReason: '原因说明',
  originalMessage: '原始信息',
  attemptHistory: '尝试时间线',
  attempts: '尝试 {0} 次',
  copyDiagnostics: '复制诊断信息',
  diagnosticsCopied: '诊断信息已复制',
  copied: '已复制',
  settingsTitle: '看板设置',
  settingsDescription:
    '配置服务商、API Key、推广网站与界面语言，保存后侧边栏批次会立即生效。',
  provider: '评论生成服务',
  configuredSites: '已配置推广网站',
  openSidePanel: '打开扩展侧边栏',
  language: '界面语言',
  languageChinese: '简体中文',
  languageEnglish: 'English',
  followsBrowser: '跟随浏览器',
  autoRefresh: '数据刷新',
  realtimeRefresh: '实时监听批次与看板变更',
  loading: '正在加载数据',
  loadFailed: '数据加载失败',
  actionFailed: '操作失败，请稍后重试',
  emptyPlanTitle: '还没有计划',
  emptyPlanHint: '创建第一个外链计划，链接会自动按批次排好。',
  selectPlan: '请选择一个计划',
  invalidConfiguredWebsite:
    '\u8bf7\u586b\u5199\u6709\u6548\u7684 HTTP(S) \u63a8\u5e7f\u843d\u5730\u9875 URL\u3002',
  invalidInput: '请修正无效链接后再保存。',
  tooManyLinks: '单个计划最多 2,000 条有效链接。',
  duplicateActiveSite: '该推广网站已有未归档计划，请先归档旧计划。',
  copyFailed: '复制失败',
  dateJoiner: '·',
  today: '今天',
  unknownPlan: '未命名计划',
  unknownSite: '未命名网站',
  itemNumber: '序号',
  selectTarget: '选择链接',
  unknownErrorReason: '运行未完成，暂时没有更多错误信息。',
  noCommentFormReason: '目标页面没有检测到可用的评论表单。',
  validationReason: '评论表单拒绝了提交内容，请检查必填字段。',
  commentBodyLinkRequiredReason:
    '提交前链接校验失败：评论正文中的推广链接缺失，或与配置的网站地址不一致。请检查 HTTP/HTTPS、域名和路径。',
  loginReason: '该页面要求先登录，完成登录后可以继续运行。',
  captchaReason: '该页面需要人工完成验证码。',
  genericFailureReason: '处理目标页面时发生错误。',
  archiveSuccess: '计划已归档',
  deleteSuccess: '计划已永久删除',
  startedSuccess: '批次已启动',
  stoppedSuccess: '批次已停止',
  retryStarted: '已开始重试',
};

const en: Record<keyof typeof zh, string> = {
  appName: 'Comment Link Assistant',
  dashboard: 'Dashboard',
  plans: 'Plans',
  settings: 'Settings',
  filterList: 'Filter list',
  filterListTitle: 'Filter list',
  filterListDescription:
    'Matching links are skipped before processing. An exact URL filters only that link; a domain also filters its subdomains.',
  filterValue: 'Link or domain',
  filterValuePlaceholder: 'https://example.com/article or example.com',
  filterMatchType: 'Match type',
  filterKindUrl: 'Exact URL',
  filterKindDomain: 'Domain and subdomains',
  addFilterEntry: 'Add filter',
  filterEntries: 'Filters ({0})',
  filterListAutoSkip: 'Future matches skip automatically',
  filterListEmptyTitle: 'No filtered links yet',
  filterListEmptyHint: 'Add one here, or add it while removing a plan link.',
  filterCreatedAt: 'Added {0}',
  removeFilterEntry: 'Remove {0} from the filter list',
  filterEntryAdded: 'Added to the filter list',
  filterEntryRemoved: 'Removed from the filter list',
  filterValueInvalid: 'Enter a valid HTTP(S) URL or domain.',
  filterListLoadFailed: 'Could not load the filter list',
  outboundLinkLibrary: 'Link library',
  outboundLinkLibraryTitle: 'Outbound link library',
  outboundLinkLibraryDescription:
    'Save executable blog article URLs and track dofollow, nofollow, anonymous-comment, and CAPTCHA attributes. Supports Excel/CSV/TXT imports.',
  outboundLinkUrl: 'Blog article URL',
  outboundLinkUrlPlaceholder: 'https://example.com/blog/article',
  outboundLinkAdd: 'Add link',
  outboundLinkEntries: 'Links ({0})',
  outboundLinkTags: 'Tags',
  outboundLinkAttributes: 'Link attributes',
  outboundLinkUnmarked: 'Unmarked',
  outboundLinkTagDofollow: 'Dofollow',
  outboundLinkTagNofollow: 'Nofollow',
  outboundLinkTagLoginRequired: 'Login required',
  outboundLinkTagCaptchaRequired: 'CAPTCHA required',
  outboundLinkNoTags: 'No tags',
  outboundLinkManualOnly: 'Full URL records',
  outboundLinkEmptyTitle: 'No outbound links yet',
  outboundLinkEmptyHint:
    'Add a site, then record its link attributes and manual handling requirements.',
  outboundLinkSaved: 'Saved to link library',
  outboundLinkUpdated: 'Outbound link updated',
  outboundLinkRemoved: 'Removed from link library',
  outboundLinkUrlInvalid: 'Enter a valid blog article URL or domain.',
  outboundLinkDuplicate: 'That complete URL is already in the link library.',
  outboundLinkAlreadyExists:
    'That complete URL is already in the link library.',
  outboundLinkTagConflict: 'Dofollow and nofollow cannot both be selected.',
  outboundLinkNotFound:
    'That outbound link no longer exists and was removed here.',
  outboundLinkUpdatedAt: 'Updated {0}',
  outboundLinkSave: 'Save link',
  editOutboundLinkEntry: 'Edit outbound link {0}',
  removeOutboundLinkEntry: 'Remove {0} from link library',
  cancelEdit: 'Cancel edit',
  outboundLinkLoadFailed: 'Could not load the link library',
  outboundLinkDomain: 'Blog article URL',
  outboundLinkFollowStatus: 'Link attribute',
  outboundLinkLoginRequired: 'Login required',
  outboundLinkCaptchaRequired: 'CAPTCHA required',
  outboundLinkStatDomains: 'Total links',
  outboundLinkStatDofollow: 'Dofollow',
  outboundLinkStatNofollow: 'Nofollow',
  outboundLinkStatAnonymous: 'Anonymous comments',
  outboundLinkStatNoCaptcha: 'No CAPTCHA',
  outboundLinkImport: 'Import file',
  outboundLinkImportPreview: 'Import preview',
  outboundLinkImportValidRows: 'valid rows',
  outboundLinkImportInvalidRows: 'invalid rows',
  outboundLinkImportConfirm: 'Confirm import',
  outboundLinkImportFailed: 'Could not parse the file',
  outboundLinkImportCompleted: 'Link library import completed',
  outboundLinkImportRowError: 'Row {0}: {1}',
  outboundLinkDownloadTemplate: 'Download template',
  outboundLinkSearch: 'Search links or domains',
  outboundLinkFilter: 'Filter attributes',
  outboundLinkFilterAll: 'All',
  outboundLinkSelect: 'Select from library',
  outboundLinkAddToPlan: 'Add to plan',
  outboundLinkSelectedCount: '{0} selected',
  outboundLinkSelectCurrentPage: 'Select current page',
  outboundLinkClearCurrentPage: 'Clear current page',
  outboundLinkSelectEmptyHint:
    'There are no selectable links. Add one in the outbound link library first.',
  outboundLinkOpenLibrary: 'Open link library',
  connected: 'Extension connected',
  disconnected: 'Extension disconnected',
  version: 'Version',
  dashboardTitle: 'Operations Dashboard',
  plansTitle: 'Plan Management',
  refresh: 'Refresh',
  refreshing: 'Refreshing',
  activePlans: 'Active plans',
  processed: 'Processed',
  submitted: 'Successful',
  failed: 'Failed',
  todaySchedule: "Today's schedule",
  runToday: "Run today's batch",
  running: 'Running',
  runBatch: 'Run batch',
  viewDetail: 'View details',
  batchProgress: 'Batch {0} of {1}',
  linkCount: '{0} links',
  nextBatch: 'Next batch',
  noNextBatch: 'This is the final batch',
  noSchedule: 'No batches scheduled for today',
  noScheduleHint:
    'The earliest pending batch will appear here after you create a plan.',
  liveRun: 'Live run',
  currentTarget: 'Currently processing',
  waitingToRun: 'Waiting to run',
  noActiveRun: 'No batch is running',
  noActiveRunHint: 'Start one from the schedule or a plan detail.',
  planProgress: 'Plan progress',
  batchProgressLabel: 'Batch progress (Batch {0})',
  remaining: 'Remaining',
  openCurrent: 'Open current link',
  stopBatch: 'Stop batch',
  continueBatch: 'Done, continue',
  websiteStats: 'Website statistics',
  promotingSites: 'Promoting sites',
  targetDomains: 'Target blog domains',
  website: 'Website',
  total: 'Total',
  recentFailures: 'Recent failures',
  allFailures: 'View plan details',
  noFailures: 'No recent failures',
  errorCode: 'Error code',
  retry: 'Retry',
  retrySelected: 'Retry selected',
  retrying: 'Retrying',
  planList: 'Plans',
  planCount: '{0} plans',
  newPlan: 'New plan',
  addPromotingSite: 'Add promoting site',
  addPromotingSiteOption: '+ Add promoting site…',
  active: 'Active',
  completed: 'Completed',
  archived: 'Archived',
  notStarted: 'Not started',
  completedWithErrors: 'Completed with errors',
  blocked: 'Needs attention',
  interrupted: 'Stopped',
  planDetail: 'Plan details',
  linksAndBatch: '{0} links · {1} per batch · {2} completed',
  batchNumber: 'Batch {0}',
  currentBatch: 'Current batch',
  targets: 'Link list',
  targetAddress: 'Link',
  status: 'Status',
  updatedAt: 'Updated',
  targetActions: 'Actions',
  deleteTargetAction: 'Delete {0}',
  deleteTargetUnavailable:
    'The current batch is running and cannot be changed yet.',
  deleteTargetTitle: 'Delete this link?',
  deleteTargetDescription:
    'This removes the link and its run history from the current plan.',
  deleteTargetPublishedHint:
    'If the comment was already published, removing this record will not retract it.',
  addToFilterList: 'Also add to the filter list',
  addToFilterListHint:
    'This exact link will be skipped automatically in future batches.',
  targetDeleted: 'Link removed from the plan',
  targetDeletedAndFiltered: 'Link removed and added to the filter list',
  confirmTargetDelete: 'Delete link',
  previousPage: 'Previous',
  nextPage: 'Next',
  pageOf: 'Page {0} of {1}',
  noTargets: 'No link data in this batch',
  submittedStatus: 'Submitted',
  publishedStatus: 'Published',
  pendingModerationStatus: 'Submitted, awaiting moderation',
  unconfirmedStatus: 'Submission unconfirmed',
  failedStatus: 'Failed',
  filteredStatus: 'Filtered',
  pendingStatus: 'Pending',
  queuedStatus: 'Queued',
  openingStatus: 'Opening page',
  analyzingStatus: 'Analyzing',
  generatingStatus: 'Generating comment',
  preparedStatus: 'Preparing',
  submittingStatus: 'Submitting',
  verifyingStatus: 'Verifying',
  loginRequiredStatus: 'Login required',
  captchaRequiredStatus: 'CAPTCHA required',
  noFormStatus: 'No comment form',
  validationErrorStatus: 'Validation failed',
  stoppedStatus: 'Stopped',
  unknownStatus: 'Unknown',
  runStage: 'Run stages',
  nextRunCard: 'Next: Batch {0}, {1} links',
  expectedStart: 'Available after the current batch finishes',
  planName: 'Plan name',
  planNamePlaceholder: 'e.g. Seed Audio July outreach',
  promotingWebsite: 'Promoting website',
  promotingSiteCreateDescription:
    'Create a promoting site that can be used by a plan.',
  promotingSiteName: 'Promoting site name',
  promotingSiteNamePlaceholder: 'e.g. Seed Audio',
  promotingSiteUrl: 'Promoting site URL',
  promotingSiteUrlPlaceholder: 'example.com',
  promotingSiteDisplayName: 'Comment display name',
  promotingSiteEmail: 'Comment email',
  promotingSiteLinkMode: 'Link mode',
  promotingSiteLinkModeATagNewline: 'a tag (new line)',
  promotingSiteLinkModeWebsiteField: 'Prefer Website field',
  promotingSiteLinkModeCommentOnly: 'Comment text only',
  addingPromotingSite: 'Saving',
  promotingSiteCreated: 'Promoting site created',
  promotingSiteNameRequired: 'Enter a promoting site name.',
  promotingSiteNameTooLong:
    'The promoting site name cannot exceed 100 characters.',
  promotingSiteUrlRequired: 'Enter a promoting site URL.',
  promotingSiteUrlInvalid: 'Enter a valid HTTP(S) URL or domain.',
  promotingSiteEmailInvalid: 'Enter a valid email address.',
  promotingSiteDuplicate: 'That promoting site already exists.',
  promotingSiteLimit: 'You can configure up to 20 promoting sites.',
  promotingSiteCreateFailed: 'Could not save the promoting site. Try again.',
  renamePlan: 'Rename plan',
  renamePlanTitle: 'Rename plan',
  savePlanName: 'Save name',
  planRenamed: 'Plan name updated',
  websiteFieldUrl: 'Promoting landing page / Website field URL',
  websiteFieldUrlPlaceholder: 'https://example.com/landing-page/',
  websiteFieldUrlHint:
    'When a blog comment form has a Website / URL input, this address is filled automatically and is not repeated in the comment text.',
  websiteFieldInlineHint:
    'The current site uses inline links, so the Website field is intentionally left blank.',
  targetUrls: 'Target blog URLs',
  targetUrlsPlaceholder: 'Paste one URL per line, up to 2,000',
  batchSize: 'Links per batch',
  importFile: 'Import TXT / CSV / Excel',
  fileHint: 'Supports .txt, .csv, .xlsx, and .xls. File contents are appended.',
  preview: 'Batch preview',
  validLinks: 'Valid links',
  duplicateLinks: 'Duplicates',
  invalidLinks: 'Invalid',
  batches: 'Estimated batches',
  showMore: '{0} more not shown',
  createPlan: 'Save plan',
  creatingPlan: 'Saving',
  cancel: 'Cancel',
  close: 'Close',
  planCreated: 'Plan created',
  archivePlan: 'Archive plan',
  archiveConfirm:
    'The plan will become read-only while all run history stays available.',
  deleteForever: 'Delete permanently',
  deleteConfirmTitle: 'Permanently delete this plan?',
  deleteConfirm:
    'This removes the plan, batches, link results, and error history. It cannot be undone.',
  confirmDelete: 'Delete permanently',
  startNextBatch: 'Run next batch',
  resumeBatch: 'Resume batch',
  errorDetail: 'Error details',
  linkProcessDetail: 'Link processing details',
  latestUpdate: 'Latest result',
  processingFlow: 'Extension processing flow',
  writtenContent: 'Content written',
  noWrittenContent: 'No comment content was generated for this attempt.',
  friendlyReason: 'What happened',
  originalMessage: 'Original message',
  attemptHistory: 'Attempt timeline',
  attempts: '{0} attempts',
  copyDiagnostics: 'Copy diagnostics',
  diagnosticsCopied: 'Diagnostics copied',
  copied: 'Copied',
  settingsTitle: 'Dashboard settings',
  settingsDescription:
    'Configure the provider, API keys, promoting sites, and interface language. Side panel batches use these settings as soon as you save.',
  provider: 'Comment service',
  configuredSites: 'Configured promoting sites',
  openSidePanel: 'Open extension side panel',
  language: 'Language',
  languageChinese: '简体中文',
  languageEnglish: 'English',
  followsBrowser: 'Follows browser',
  autoRefresh: 'Data refresh',
  realtimeRefresh: 'Listens for batch and dashboard changes',
  loading: 'Loading data',
  loadFailed: 'Could not load data',
  actionFailed: 'Action failed. Please try again.',
  emptyPlanTitle: 'No plans yet',
  emptyPlanHint:
    'Create your first outreach plan and links will be batched automatically.',
  selectPlan: 'Select a plan',
  invalidConfiguredWebsite:
    'Set a valid HTTP(S) URL for this promoting website in Settings first.',
  invalidInput: 'Fix invalid links before saving.',
  tooManyLinks: 'A plan can contain up to 2,000 valid links.',
  duplicateActiveSite:
    'This site already has an unarchived plan. Archive it first.',
  copyFailed: 'Copy failed',
  dateJoiner: '·',
  today: 'Today',
  unknownPlan: 'Untitled plan',
  unknownSite: 'Unnamed site',
  itemNumber: '#',
  selectTarget: 'Select link',
  unknownErrorReason: 'The run did not finish and has no further details.',
  noCommentFormReason: 'No usable comment form was found on the target page.',
  validationReason:
    'The comment form rejected the submission. Check required fields.',
  commentBodyLinkRequiredReason:
    'Pre-submit link validation failed: the promoted link is missing from the comment body or does not match the configured website URL. Check the protocol, host, and path.',
  loginReason: 'This page requires login. Continue after signing in.',
  captchaReason: 'This page requires a person to complete a CAPTCHA.',
  genericFailureReason: 'An error occurred while processing this target.',
  archiveSuccess: 'Plan archived',
  deleteSuccess: 'Plan permanently deleted',
  startedSuccess: 'Batch started',
  stoppedSuccess: 'Batch stopped',
  retryStarted: 'Retry started',
};

export type CopyKey = keyof typeof zh;

export function locale(): 'zh-CN' | 'en' {
  return getUiLocale();
}

export function t(
  key: CopyKey,
  substitutions: Array<string | number> = []
): string {
  const template = locale() === 'zh-CN' ? zh[key] : en[key];
  return substitutions.reduce<string>(
    (copy, value, index) => copy.replaceAll(`{${index}}`, String(value)),
    template
  );
}
